filter:
    paths: [ 'src/*' ]

build:
    nodes:
        analysis:
            project_setup:
                override: true
            environment:
                php:
                    version: 8.1
                    compile_options: '--with-openssl --with-curl --enable-mbstring --enable-mbregex --enable-bcmath --with-mhash --with-xmlrpc --enable-opcache --enable-intl --with-pear --enable-fpm --with-zlib-dir --enable-inline-optimization --with-bz2 --with-zlib'
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis

checks:
    php:
        code_rating: true
        duplication: false
        verify_property_names: true
        uppercase_constants: true
        remove_extra_empty_lines: true
        properties_in_camelcaps: true
        parameters_in_camelcaps: true
        overriding_parameter: true
        optional_parameters_at_the_end: true
        function_in_camel_caps: true
        encourage_single_quotes: true
        classes_in_camel_caps: true
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
        avoid_perl_style_comments: true
        avoid_usage_of_logical_operators: true
        no_exit: false
        no_unnecessary_final_modifier: false
        overriding_private_members: false
