checks:
    php: true

coding_style:
    php:
        spaces:
            before_parentheses:
                closure_definition: true
            around_operators:
                concatenation: true

build:
    nodes:
        main:
            before_commands:
                - sudo apt-get update
                - sudo apt-get install -y openssl
