services:
    locastic_api_platform_translation.translation.translator:
        class: Locastic\ApiPlatformTranslationBundle\Translation\Translator
        arguments:
            - '@translator'
            - '@request_stack'
            - '%kernel.default_locale%'

    locastic_api_platform_translation.listener.assign_locale:
        class: Locastic\ApiPlatformTranslationBundle\EventListener\AssignLocaleListener
        arguments:
            - '@locastic_api_platform_translation.translation.translator'
            - '%kernel.default_locale%'
        tags:
            - { name: doctrine.event_listener, event: postLoad }
            - { name: doctrine.event_listener, event: prePersist }

# Filters
    locastic_api_platform_translation.filter.translation_groups:
        parent: 'api_platform.serializer.group_filter'
        tags:
            - { name: 'api_platform.filter', id: 'translation.groups' }
