name: PHPUnit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php-versions }} ${{ matrix.dependencies }}
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.2', '8.3', '8.4', '8.5']
        dependencies: ['highest']
        include:
          - php-versions: '8.2'
            dependencies: 'lowest'
    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
    - name: Install dependencies (highest)
      if: matrix.dependencies == 'highest'
      run: composer update --no-interaction --prefer-dist
    - name: Install dependencies (lowest)
      if: matrix.dependencies == 'lowest'
      run: composer update --no-interaction --prefer-dist --prefer-lowest --prefer-stable
    - name: Validate composer.json
      run: composer validate --strict
    - name: Run tests
      run: bin/phpunit
